#theme = "onedark"
#theme = "catppuccin_mocha"
theme = "rose_pine"
[editor]
line-number = "relative"
cursorline = true
color-modes = true
true-color = true
[keys.normal]
esc = ["collapse_selection","keep_primary_selection"]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
